name: Reusable workflow example

on:
  workflow_call:
    inputs:
      param:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  parent:
    runs-on: ubuntu-latest
    steps:
     - run: echo ${{ inputs.config-path }}
        
