name: Reusable workflow example

on:
  workflow_call:
    inputs:
      param:
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
     - run: echo ${{ inputs.config-path }}
  job2:
    runs-on: ubuntu-latest
    steps:
     - run: echo "123"
        
